language: cpp
dist: trusty

addons:
    apt:
        packages:
        - tclsh
        - pkg-config
        - cmake
        - libssl-dev
        - build-essential

matrix:
    include:
        - env: BUILD_TYPE=Debug
        - env: BUILD_TYPE=Release
        - os: osx
          osx_image: xcode7.3
          env: BUILD_TYPE=Debug
          before_install: brew update
          install: brew install openssl gnutls nettle
        - os: osx
          osx_image: xcode7.3
          before_install: brew update
          install: brew install openssl gnutls nettle
          env: BUILD_TYPE=Release


script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ];   then cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=/usr/local/opt/openssl; fi
    - make
